"""
RL Environment for 2x2 Grid Intersection.

State (16-tuple):
    (sig_TL, q1_TL, q2_TL, busy_TL,
     sig_TR, q1_TR, q2_TR, busy_TR,
     sig_BL, q1_BL, q2_BL, busy_BL,
     sig_BR, q1_BR, q2_BR, busy_BR)

    Per node: sig=True means E-W group has green, q1=E-W queue, q2=N-S queue.

Action space: 0..15  (4-bit mask, one bit per intersection)
    bit 0 -> switch TL
    bit 1 -> switch TR
    bit 2 -> switch BL
    bit 3 -> switch BR

For the math/network agent, actions are generated by decentralized per-node
decisions and encoded with encode_action(). Direct RL training over all 16
actions is also supported.
"""

from typing import Optional, Tuple

from TrafficSimulator import Simulation
from TrafficSimulator.Setups.grid_intersection import (
    grid_intersection_setup,
    TL_THROUGH_ROADS,
    TR_THROUGH_ROADS,
    BL_THROUGH_ROADS,
    BR_THROUGH_ROADS,
)

THROUGH_SETS = [TL_THROUGH_ROADS, TR_THROUGH_ROADS,
                BL_THROUGH_ROADS, BR_THROUGH_ROADS]

MAX_GEN = 120   # scaled up for 4 intersections


def encode_action(sw_tl: bool, sw_tr: bool, sw_bl: bool, sw_br: bool) -> int:
    """Encode four switch decisions as a single integer 0-15."""
    return (int(sw_tl)
            | (int(sw_tr) << 1)
            | (int(sw_bl) << 2)
            | (int(sw_br) << 3))


def decode_action(action: int) -> Tuple[bool, bool, bool, bool]:
    """Decode action integer to (sw_tl, sw_tr, sw_bl, sw_br)."""
    return (bool(action & 1),
            bool(action & 2),
            bool(action & 4),
            bool(action & 8))


class GridEnvironment:
    """Gym-style environment for the 2x2 grid intersection."""

    def __init__(self):
        self.action_space = list(range(16))
        self.sim: Optional[Simulation] = None
        self._prev_inbound: int = 0

    def step(self, action: int) -> Tuple[Tuple, float, bool, bool]:
        sw_tl, sw_tr, sw_bl, sw_br = decode_action(action)
        self.sim.run_with_actions([sw_tl, sw_tr, sw_bl, sw_br])

        new_state  = self.get_state()
        reward     = self.get_reward(new_state)
        self._prev_inbound = sum(new_state[i] for i in (1,2, 5,6, 9,10, 13,14))

        return new_state, reward, self.sim.completed, self.sim.gui_closed

    def reset(self, render: bool = False) -> Tuple:
        self.sim = grid_intersection_setup(MAX_GEN)
        if render:
            self.sim.init_gui()
        self._prev_inbound = 0
        return self.get_state()

    def get_state(self) -> Tuple:
        """Build the 16-tuple state from the current simulation."""
        state = []
        for sig_idx, sig in enumerate(self.sim.traffic_signals):
            sig_state = bool(sig.current_cycle[0])
            q1 = sum(len(r.vehicles) for r in sig.roads[0])
            q2 = sum(len(r.vehicles) for r in sig.roads[1])
            busy = any(
                len(self.sim.roads[i].vehicles) > 0
                for i in THROUGH_SETS[sig_idx]
                if i in self.sim.non_empty_roads
            )
            state.extend([sig_state, q1, q2, busy])
        return tuple(state)

    def get_reward(self, state: Tuple) -> float:
        """Reward = decrease in total inbound queue vs previous step."""
        total_now = sum(state[i] for i in (1, 2, 5, 6, 9, 10, 13, 14))
        return float(self._prev_inbound - total_now)
